name: Build Archlinux Packages

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 9,21 * * 1-6' # build pkgs via 996 rules (；′⌒`)
  workflow_dispatch: # allow manual trigger

jobs:
  Build: # build packages
    strategy:
      matrix:
        pkgs: [wps-office, plasma5-wallpapers-dynamic, imgui, kwin-script-grid-tiling-git, index-generator, xwinwrap-git, wps-office-mui-zh-cn, ttf-wps-fonts, nordic-kde-git, mesen-git] # package list 
      fail-fast: false # allow package build fails
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Build pkgs in above list 
        uses: zjuyk/pkgbuild-aur@master
        with:
          pkg-name: ${{ matrix.pkgs }}
      - name: Upload assets to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "packages"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Send notify to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            From ${{ github.repository }} / ${{ github.workflow }}: 
                Package ${{ matrix.pkgs }} build success!
            [URL](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

